ARG BASE="noble-full"
FROM ghcr.io/koush/scrypted-common:${BASE}

# avahi advertiser support
RUN apt-get update && apt-get -y install \
    libnss-mdns \
    avahi-discover \
    libavahi-compat-libdnssd-dev \
    xz-utils \
    psmisc

COPY install/docker/fs /

ARG S6_OVERLAY_VERSION=3.1.5.0
ENV S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
ENV S6_KEEP_ENV=1
ARG TARGETARCH
RUN case "${TARGETARCH}" in \
      amd64) S6_ARCH='x86_64';; \
      arm) S6_ARCH='armhf';; \
      arm64) S6_ARCH='aarch64';; \
      *) echo "Your system architecture isn't supported."; exit 1;; \
    esac \
    && cd /tmp \
    && curl -SLOf "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz" \
    && tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz \
    && curl -SLOf "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-${S6_ARCH}.tar.xz" \
    && tar -C / -Jxpf "/tmp/s6-overlay-${S6_ARCH}.tar.xz"

ENTRYPOINT ["/init"]

WORKDIR /
COPY install/docker/dist/scrypted-server.tgz /tmp/scrypted-server.tgz
RUN npm --prefix /server install --omit=dev /tmp/scrypted-server.tgz \
    && rm /tmp/scrypted-server.tgz
WORKDIR /server

ENV NODE_OPTIONS="--dns-result-order=ipv4first"
ENV SCRYPTED_BASE_VERSION="20250101"

CMD ["/bin/sh", "-c", "ulimit -c 0; exec npm --prefix /server exec scrypted-serve"]
